version: '3.1'

services:

  wordpress:
    image: wordpress:6.4.2-php8.1-apache
    restart: always
    ports:
      - ${APP_PORT}:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_LOCALE: ${APP_LANG}
    volumes:
      - ./wordpress:/var/www/html/wp-content/themes
      - ./docker/server/.htaccess:/var/www/html/.htaccess
      - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - wp_net

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - wp_net

volumes:
  wordpress:
  db:

networks:
  wp_net: